## eigendecomposition exercise

In [64]:
# import numpy
import numpy as np
import cmath

**Task:** Create a matrix (2x2) called matrix 'A'.


In [65]:
A = np.array([[5, 1], [3, 3]])

In [66]:
B = np.array([[5, 1], [3, 3], [3, 3]])

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [67]:
"""
Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

PARAMS:
    matrix (numpy.ndarray) - matrix to check
RETURN:
    True (bool) - if matrix has shape 2x2
    False (bool) - if matrix has not shape 2x2

"""


"\nDefine the function 'shape_2x2' which checks if a matrix has a (2x2) shape.\n\nPARAMS:\n    matrix (numpy.ndarray) - matrix to check\nRETURN:\n    True (bool) - if matrix has shape 2x2\n    False (bool) - if matrix has not shape 2x2\n\n"

In [68]:
def shape_2x2(matrix):
    if matrix.shape == (2,2):
      return True
    return False

In [69]:
shape_2x2(A)

True

**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [70]:
"""
Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

PARAMS:
    matrix (numpy.ndarray) - matrix to compute determinant
RETURN:
    det (float) - matrix determinant

"""


"\nDefine the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.\n\nPARAMS:\n    matrix (numpy.ndarray) - matrix to compute determinant\nRETURN:\n    det (float) - matrix determinant\n\n"

**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [71]:
def determinant(matrix):
   return np.linalg.det(matrix)

In [72]:
determinant(A)

11.999999999999995

**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [73]:
Eigen = np.linalg.eig(A)

In [74]:
Eigen

(array([6., 2.]),
 array([[ 0.70710678, -0.31622777],
        [ 0.70710678,  0.9486833 ]]))

**Task:** Print the eigenvalues.

In [75]:
Eigen[0]

array([6., 2.])

**Task:** Print  the eigenvectors.

In [76]:
Eigen[1]

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?:

- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [77]:
"""
Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

"""

"\nDefine a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix\n\nPARAMS:\n    matrix (numpy.ndarray) - matrix to perform decomposition\nRETURN:\n    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays\n\n"

In [78]:
np.trace(A)

8

In [79]:
# Solve the quadratic equation ax**2 + bx + c = 0

# import complex math module
import cmath

a = 
b = 5
c = 6

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

SyntaxError: invalid syntax (1045144603.py, line 6)

**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [80]:
def eig_2x2(matrix):
   a = 1
   b = matrix.trace()
   c = np.linalg.det(matrix)
   d = (b**2) - (4*a*c)
   sol1 = (-b-cmath.sqrt(d))/(2*a)
   sol2 = (-b+cmath.sqrt(d))/(2*a) 
 (sol1, sol2)

In [81]:
eig_2x2(A)


((-6.000000000000002+0j), (-1.9999999999999987+0j))

**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [43]:
np.allclose(Eigen[0], eigen2[0])


True

In [44]:
np.allclose(Eigen[1], eigen2[1])

True

**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [45]:
B = np.array([[0, 1], [-1, 0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [46]:
eig_2x2(B)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        +0.70710678j, 0.        -0.70710678j]]))

**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?